### PR TITLE
Update to v1.11.1

### PR DESCRIPTION
**Pull request by tmewett**

### CODE REVIEW

**Comment by tmewett** [comment]
Hi @jjardon :) Just a question, if you don't mind: is there a way a Flatpak user can easily download and test this staging build before I publish it?

**Comment by tmewett** [comment]
Oh... well that'll be how :laughing:

**Comment by jjardon** [comment]
Hey @tmewett ! :) See just above ^ :)

**Comment by WauloK** [comment]
Yeah that works for me! Thanks! :)

**Pull request merged**
